#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Authors:
#Alan D. Snow, 2016, based on initial .yml file by Cedric H. David


#*******************************************************************************
#System specifications for Travis CI
#*******************************************************************************
language: python
python:
  - "2.7"
  - "3.5"
notifications:
  email: false

#*******************************************************************************
#Before installing RAPIDpy
#*******************************************************************************
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y g++ gfortran

#-------------------------------------------------------------------------------
#Add miniconda - from https://gist.github.com/dan-blanchard/7045057
#-----------------------------------------------------------------------------
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda update --yes conda
#create environment in conda
- conda create --name rapid python=$TRAVIS_PYTHON_VERSION
- source activate rapid

#-------------------------------------------------------------------------------
# Install required python packages
#-----------------------------------------------------------------------------
- conda install --yes nose numpy scipy netCDF4 gdal shapely pyproj
#- export GDAL_DATA=$HOME/miniconda/share/gdal
- conda install --yes -c conda-forge rtree
- pip install coveralls

#-------------------------------------------------------------------------------
#Creating directory for installation of libraries used by RAPID
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- mkdir ../installz
- cd ../installz
- export INSTALLZ_DIR=$PWD

#-------------------------------------------------------------------------------
#Installing netCDF 3.6.3
#-------------------------------------------------------------------------------
- cd $INSTALLZ_DIR
- wget "ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-3.6.3.tar.gz"
- mkdir netcdf-3.6.3-install
- tar -xf netcdf-3.6.3.tar.gz
- cd netcdf-3.6.3
- ./configure --prefix=$INSTALLZ_DIR/netcdf-3.6.3-install
- make check
- make install

#-------------------------------------------------------------------------------
#Installing PETSc 3.6.2
#-------------------------------------------------------------------------------
- cd $INSTALLZ_DIR
- wget "http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.6.2.tar.gz" 
- tar -xf petsc-3.6.2.tar.gz
- cd petsc-3.6.2
- python2 './configure' 'PETSC_DIR='$PWD 'PETSC_ARCH=linux-gcc-cxx' '--download-fblaslapack=1' '--download-mpich=1' '--with-cc=gcc' '--with-cxx=g++' '--with-fc=gfortran' '--with-clanguage=cxx' '--with-debugging=0'
- make PETSC_DIR=$PWD PETSC_ARCH=linux-gcc-cxx all
- make PETSC_DIR=$PWD PETSC_ARCH=linux-gcc-cxx test

#-------------------------------------------------------------------------------
#Exporting environment variables 
#-------------------------------------------------------------------------------
- export TACC_NETCDF_LIB=$INSTALLZ_DIR/netcdf-3.6.3-install/lib
- export TACC_NETCDF_INC=$INSTALLZ_DIR/netcdf-3.6.3-install/include
- export PETSC_DIR=$INSTALLZ_DIR/petsc-3.6.2
- export PETSC_ARCH='linux-gcc-cxx'

#-------------------------------------------------------------------------------
#Exporting directories with library-related executables to $PATH
#-------------------------------------------------------------------------------
- export PATH=$PATH:/$PETSC_DIR/$PETSC_ARCH/bin
- export PATH=$PATH:$INSTALLZ_DIR/netcdf-3.6.3-install/bin

#-------------------------------------------------------------------------------
#Installing RAPID
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- cd ..
- git clone https://github.com/c-h-david/rapid.git
- cd rapid/src
- make rapid

#*******************************************************************************
#Installing RAPIDpy
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- python setup.py install
#*******************************************************************************
#Testing RAPIDpy
#*******************************************************************************
- cd $TRAVIS_BUILD_DIR/tests
script: 
- nosetests --with-coverage --cover-package=RAPIDpy
##ADD Coveralls stats for code coverage
after_success:
  - coveralls
